Проверка
файла new.py не окажется в итоге в репозитории